SELECT
CUSTOMER_STATE
,CUSTOMER_CITY
,COUNT(DISTINCT CUSTOMER_ID) AS COUNT_OF_CUSTOMERS

FROM EXAMPLE.CUSTOMER
WHERE CUSTOMER_ID IS NOT NULL
AND CUSTOMER_STATE = 'MO'

GROUP BY 
CUSTOMER_STATE
,CUSTOMER_CITY
WITH UR;
        