SELECT
STORE_NUMBER
,STORE_STATE
,MAX(DECODE(CUSTOMER_GENDER, 'F', CUSTOMER_COUNT) AS COUNT_OF_FEMALE_CUSTOMERS
,MAX(DECODE(CUSTOMER_GENDER, 'M', CUSTOMER_COUNT) AS COUNT_OF_MALE_CUSTOMERS
,MAX(DECODE(CUSTOMER_GENDER, 'U', CUSTOMER_COUNT) AS COUNT_OF_UNKNOWN_CUSTOMERS

FROM(
SELECT
STORE_NUMBER
,STORE_STATE
,CUSTOMER_GENDER
,SUM(CUSTOMER_ID) AS CUSTOMER_COUNT

FROM EXAMPLE.CUSTOMER
WHERE STORE_STATE IS NOT NULL

GROUP BY
STORE_NUMBER
,STORE_STATE
,CUSTOMER_GENDER
)

GROUP BY
STORE_NUMBER
,STORE_STATE

ORDER BY
STORE_NUMBER
,STORE_STATE
WITH UR;
