SELECT
STORE_ID
,STORE_STATE
,STORE_CITY
,ROW_NUMBER() OVER(PARTITION BY STORE_ID ORDER BY COUNT(*) DESC, STORE_STATE) AS STORE_STATE_RANK

FROM EXAMPLE.STORE
WHERE STORE_ID IS NOT NULL
AND (STORE_INACTIVE_DATE >= '2019-08-31' OR 
STORE_INACTIVE_DATE IS NULL)

GROUP BY 
STORE_ID
,STORE_STATE
,STORE_CITY

WITH UR;
        